# Generated by Django 2.0.3 on 2019-07-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='date',
        ),
    ]
