# Generated by Django 2.0.3 on 2019-07-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_watchlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='profile_id',
            field=models.IntegerField(default=1),
        ),
    ]
